--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: codeserver-pvc 
  namespace: codeserver 
  labels: 
    app: codeserver 
    name: codeserver-pvc 
spec: 
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
