---
apiVersion: v1 
kind: Namespace 
metadata: 
  name: dov-ns 
  labels:
    app: dov 
    name: dov-ns

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: dov-deploy
  namespace: dov-ns 
  labels:
    app: dov 
    name: dov-deploy
spec:
  # number of instance
  replicas: 3
  # select pods belonging to this deployment
  selector:
    matchLabels:
      app: dov 
      name: dov-po
  # pod template
  template:
    metadata:
      name: dov-po 
      labels:
        app: dov 
        name: dov-po
    spec:
      containers:
      - name: dov-container
        image: stackupiss/dov-bear:v1 
        imagePullPolicy: IfNotPresent 
        env:
        - name: INSTANCE_NAME 
          value: dov-bear
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc 
  namespace: dov-ns 
  labels:
    app: dov 
    name: dov-svc 
spec:
  type: ClusterIP
  selector:
    app: dov
    name: dov-po
  ports: 
  - port: 8080
    targetPort: 3000

--- 
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: dov-ing
  namespace: dov-ns 
  labels: 
    app: dov 
    name: dov-ing
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/limit-rps: "5"

spec:
  ingressClassName: nginx
  rules:
  - host: dov-139.59.195.68.nip.io
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend: 
          service:
            name: dov-svc
            port: 
              number: 8080