---
apiVersion: v1
kind: Namespace 
metadata:
  name: minio 
  labels:
    name: minio
    app: minio

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  labels:
    name: minio-secret
    app: minio
  namespace: minio
data:
  # admin
  MINIO_ROOT_USER: YWRtaW4=
  # hello, world
  MINIO_ROOT_PASSWORD: aGVsbG8sIHdvcmxk